In [1]:
# formas de lidar com dados em falta, deixar entradas vazias, apagar linha ou coluna, preencher com media da coluna, existem mais formas que devem ser usadas dependendo do caso.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("anime_20linhas.csv",)
df.head(2)

,Anime_ID,Title,Genre,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,"Fantasy, Horror, Action",36,TV,J.C.Staff,Webtoon,7.67,4954,236999,39747,2026-05-17,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,"Romance, Action",58,ONA,Ufotable,Game,7.83,5484,450384,41331,2027-02-25,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...

In [4]:
df.loc[1,"Genre"]=np.nan # Coloquei a NaN para exemplo
df.loc[2,"Rating"]=np.nan
df.loc[3,"Rating"]=np.nan
df.head(4)

,Anime_ID,Title,Genre,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,"Fantasy, Horror, Action",36,TV,J.C.Staff,Webtoon,7.67,4954,236999,39747,2026-05-17,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,NaN,58,ONA,Ufotable,Game,7.83,5484,450384,41331,2027-02-25,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...
2,3,Guy explain human everybody,"Drama, Comedy",2,ONA,Wit Studio,Game,NaN,3840,871129,9746,2025-12-22,2025-12-22,46,Saturday,"Bandai Namco, Aniplex","Funimation, Crunchyroll",7.85,18212,Simple attack radio mission enjoy know. Find e...
3,4,Himself forward recent,"Supernatural, Drama",92,OVA,Wit Studio,Game,NaN,3144,515087,13067,2029-04-14,2029-04-14,57,Thursday,"Kadokawa, Bandai Namco",Netflix,8.79,8818,Second shoulder pattern. Among reality central...

In [5]:
# 1- REMOVER LINHAS COM DADOS EM FALTA

In [6]:
# REMOVE LINHAS "AXIS=0" NA COLUNA "SUBSET="RATINGS"" ONDE EXISTEM VALORES NaN
# inplace=True muda no próprio dataframe, ignore_index=True para não saltar index das linhas apagadas
df.dropna(subset="Rating",axis=0,inplace=True, ignore_index=True) 
df.head(5)

,Anime_ID,Title,Genre,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,"Fantasy, Horror, Action",36,TV,J.C.Staff,Webtoon,7.67,4954,236999,39747,2026-05-17,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,NaN,58,ONA,Ufotable,Game,7.83,5484,450384,41331,2027-02-25,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...
2,5,Out increase choose,"Adventure, Drama, Supernatural",41,TV,A-1 Pictures,Webtoon,6.45,3857,622931,17013,2026-12-15,2026-12-15,52,Sunday,"TV Tokyo, Kodansha","Viz Media, Funimation",6.44,10012,During none here. Decision chair point positio...
3,6,Big,"Romance, Fantasy",97,TV,Madhouse,Game,6.00,9001,269625,47078,2029-10-21,2029-10-21,59,Saturday,"Kodansha, Bandai Namco","Crunchyroll, Netflix",6.52,11549,Cup about Republican. Nice spend back enough.\...
4,7,Now floor hair free,"Sci-Fi, Adventure",45,ONA,J.C.Staff,Game,9.85,1086,427479,34746,2027-01-24,2027-01-24,26,Wednesday,"Bandai Namco, Kadokawa",Crunchyroll,9.85,1217,Fish use attack. Hear section yet if sort happ...

In [7]:
df.dropna(axis=1,inplace=True) #APAGA COLUNA GENRE
df.head(2)

,Anime_ID,Title,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,36,TV,J.C.Staff,Webtoon,7.67,4954,236999,39747,2026-05-17,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,58,ONA,Ufotable,Game,7.83,5484,450384,41331,2027-02-25,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...

In [8]:
df.loc[2,"Rating"]=np.nan
df.loc[3,"Rating"]=np.nan
df.head(4)

,Anime_ID,Title,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,36,TV,J.C.Staff,Webtoon,7.67,4954,236999,39747,2026-05-17,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,58,ONA,Ufotable,Game,7.83,5484,450384,41331,2027-02-25,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...
2,5,Out increase choose,41,TV,A-1 Pictures,Webtoon,NaN,3857,622931,17013,2026-12-15,2026-12-15,52,Sunday,"TV Tokyo, Kodansha","Viz Media, Funimation",6.44,10012,During none here. Decision chair point positio...
3,6,Big,97,TV,Madhouse,Game,NaN,9001,269625,47078,2029-10-21,2029-10-21,59,Saturday,"Kodansha, Bandai Namco","Crunchyroll, Netflix",6.52,11549,Cup about Republican. Nice spend back enough.\...

In [9]:
# 2 COMPLETAR DADOS EM FALTA COM A MÉDIA DA COLUNA

In [10]:
# Colocar media nos valores faltantes

media=df["Rating"].mean()
df["Rating"].replace(np.nan,media, inplace=True)
df.head(4)

C:\Users\Ricardo\AppData\Local\Temp\ipykernel_1076\4128920258.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Rating"].replace(np.nan,media, inplace=True)

,Anime_ID,Title,Episodes,Type,Studio,Source,Rating,Popularity,Members,Favorites,Airing_Start,Airing_End,Duration,Broadcast_Day,Producers,Licensors,Score,Rank,Synopsis
0,1,Teach under work,36,TV,J.C.Staff,Webtoon,7.670000,4954,236999,39747,2026-05-17,2026-05-17,54,Monday,"TV Tokyo, Kodansha",Viz Media,5.42,13948,Order per far even something of never. Natural...
1,2,Phone star,58,ONA,Ufotable,Game,7.830000,5484,450384,41331,2027-02-25,2027-02-25,50,Sunday,Kodansha,Viz Media,6.98,14869,Realize mean situation high sing. Seek could e...
2,5,Out increase choose,41,TV,A-1 Pictures,Webtoon,7.057647,3857,622931,17013,2026-12-15,2026-12-15,52,Sunday,"TV Tokyo, Kodansha","Viz Media, Funimation",6.44,10012,During none here. Decision chair point positio...
3,6,Big,97,TV,Madhouse,Game,7.057647,9001,269625,47078,2029-10-21,2029-10-21,59,Saturday,"Kodansha, Bandai Namco","Crunchyroll, Netflix",6.52,11549,Cup about Republican. Nice spend back enough.\...